#
#	File Name:	ICSColumnResource_en.properties
#	Version:	2.2.1c(dpr)
#
#	Description:
#		ISO-8859-1: \u71fc\u4efb\ufffd
#		ColumnResourceBundle\uc758 ICS\uc6a9 subSet
#
#	Note:
#		ICSBoard
#		ICSBoardHeadword
#
#	Modified	(YYYY/MM/DD)	Ver		Content
#	hankalam	2021/11/30		2.2.1c	\ud56d\ubaa9 \uba54\uc2dc\uc9c0 \ubc0f ATTR \uc218\uc815
#	hankalam	2017/02/28		2.2.1c	ICSBoard: boardNumber \uc5d0 important icon \ucd94\uac00
#										ICSHelpBoard \ucd94\uac00
#	stghr12		2010/07/31		2.2.1	version up
#	lsinji		2009/10/25		2.2.0	create
#

########################################################################################################################
#
#	[COL.]{columnKey}			{titlePattern}			Y|N	[{columnAttr}]					[{dataPattern}]
#	[COL.]{columnKey}%ATTR		{columnAttr}
#	[COL.]{columnKey}%DATA		{dataPattern}
#	[COL.]{columnKey}%HELP		{helpPattern}
#	GRP.{columnGroupKey}		{titlePattern}			[{columnAttr}]
#	GRP.{columnGroupKey}%COL	{columnKey}				[{titlePattern}]					[{columnAttr}]
#	LNK.{linkKey}				{hrefPattern}												[{titlePattern}]
#	LNK.{linkKey}%TITLE			{titlePattern}
#	LNK.{linkKey}%AUTH			{systemCode} {packageCode}
#	LNK.{linkKey}%COND			NOT_NULL|NOT_ZERO|EQUALS|CONTAINS {fieldKey} [{value1}[,{value2}[,...]]]
#	SFX.{suffixKey}				{suffixPattern}
#
########################################################################################################################


########################################################################################################################
#	ICSBoard
########################################################################################################################
ICSBoard:
	%primaryKeys( boardNumber )
	boardNumber					No						N	class='w50 align-center'		$f{decode(boardType,N,<img src='images/ico_important_unread.png' class='attach'>,decode(boardGroupLevel,0,${boardNumber})}
	title.desc					Title					N	class='description mw120 align-left'
	title.desc%DATA				$f{decode(boardGroupLevel,0,,<img src='images/board/ico_reply.gif' class='reply'>)} $H{title}
	title.desc.rd%DATA			$f{decode(boardGroupLevel,0,,<img src='images/board/ico_reply.gif' class='reply'>)} $f{decode2($H{title},readedByUser,N,<b>,</b>)}
	globalHeadwordName			Headword				N	class='w80 align-left'
	globalHeadwordName.s		Hdword					N	class='w80 align-left'
	headwordName				Head<br>word			N	class='w80 align-left'
	headwordName.s				Hdword					N	class='w80 align-left'
	registUserName				Author					N	class='w100 align-left'
	noticeStartDate				Start Date				N	class='date'					${noticeStartDate~~10}
	noticeEndDate				End Date				N	class='date'					${noticeEndDate~~10}
	createDateTime				Create Date				N	class='w110 align-right'			${createDateTime~~10}
	readedUserCount				Readed Count			N	class='w80 align-right'
	SFX.attach					$f{decode(attachedFileInd,Y,&nbsp;<img src='images/ico_download.png' class='attach'>)}
	SFX.comment					$f{decode(commentCount,0,,<span class='comment'> [${commentCount}]</span>)}
	SFX.new						$f{decode(isNew,Y,&nbsp;<img src='images/board/ico_new.gif' class='attach'>)}

	LNK.info					JavaScript:infoReq("${boardNumber}");						Content Info

ICSBoard%LIST:
	%defaultSortKeys( boardType#DESC, boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
#	%propertyValue( lineAttribute = $f{decode(boardType,N,bgcolor='#C6F4FF' style='font-weight:bold;')} )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, createDateTime headwordName
	title.desc+attach+comment+new#info/RD_N, title.desc.rd+attach+comment+new#info/RD_Y
	registUserName, readedUserCount

ICSBoard%LIST.ALL:
	%defaultSortKeys( boardType#DESC, boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%propertyValue( lineAttribute = $f{decode(boardType,N,bgcolor='#C6F4FF' style='font-weight:bold;')} )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, headwordName
	title.desc+attach+comment+new#info/RD_N, title.desc.rd+attach+comment+new#info/RD_Y
	registUserName, noticeStartDate, noticeEndDate, createDateTime, readedUserCount

ICSBoard.NOTICE%LIST:
	%defaultSortKeys( boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, title.desc/RD_N, title.desc.rd#info/RD_Y, registUserName, readedUserCount

ICSBoard.NOTICE%LIST.ALL:
	%defaultSortKeys( boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, title.desc/RD_N, title.desc.rd#info/RD_Y, registUserName, noticeStartDate, noticeEndDate, readedUserCount

ICSBoard.NONAME%LIST:
	%defaultSortKeys( boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, headwordName
	title.desc+attach+comment+new#info/RD_N, title.desc.rd+attach+comment+new#info/RD_Y
	createDateTime, readedUserCount

ICSBoard.NONAME%LIST.ALL:
	%defaultSortKeys( boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, headwordName
	title.desc+attach+comment+new#info/RD_N, title.desc.rd+attach+comment+new#info/RD_Y
	noticeStartDate, noticeEndDate, createDateTime, readedUserCount

########################################################################################################################
#	ICSBoardHeadword
########################################################################################################################
ICSBoardHeadword:
	%primaryKeys( headwordCode )
	%includeKeys( createDateTime, updateDateTime )
	boardClassCode				Board Code				N	class='w120 align-right'
	boardClassName				Board Name				N	class='w150 align-left'
	headwordCode				Headword Code			N	class='w120 align-right'
	headwordName				Headword Name			N	class='description mw200 align-left'
	updateUserId				Last Modified User		N	class='username'
	updateDateTime%ATTR										class='w110 align-right'

ICSBoardHeadword%LIST:
	boardClassName, headwordName, updateDateTime


########################################################################################################################
#	ICSHelpBoard
########################################################################################################################
ICSHelpBoard:
	%primaryKeys( boardNumber )
	boardNumber					No						N	class='w60 align-center'		$f{decode(boardGroupLevel,0,${boardNumber})}
	registUserUserId			User ID					N	class='w120 align-left'
	userName.desc				User Name				N	class='description mw150 align-left'
	userName.desc%DATA			$f{decode(boardGroupLevel,0,,<img src='images/board/ico_reply.gif' class='reply'>)} $H{userName}
	userName.desc.rd%DATA		$f{decode(boardGroupLevel,0,,<img src='images/board/ico_reply.gif' class='reply'>)} $f{decode2($H{userName},readedByUser,N,<b>,</b>)}
	headwordName				Message Type			N	class='w180 align-left'						$H{ICS_HELP_BOARD_HEADWORD_@headwordName}
	completedInd				Completed				N	class='w100 align-left'
	createDateTime				Date					N	class='w100 align-left'			<label>${createDateTime~~10}</label>
	SFX.attach					$f{decode(attachedFileInd,Y,&nbsp;<img src='images/board/ico_attach_file.gif' class='attach'>)}
	SFX.new						$f{decode(isNew,Y,&nbsp;<img src='images/board/ico_new.gif' class='attach'>)}

	LNK.info					JavaScript:infoReq("${boardNumber}");										Content Info

ICSHelpBoard%LIST:
	%defaultSortKeys( boardGroupNumber#DESC, boardGroupDisplaySeq#ASC )
	%propertyValue( lineAttribute = $f{decode(completedInd,Y,bgcolor='#C6F4FF')} )
	%hiddenKeys( afterRegisteredDays )
	boardNumber, registUserUserId, userName.desc+attach+new#info/RD_N, userName.desc.rd+attach+new#info/RD_Y
	headwordName, createDateTime, completedInd
