########################################################################################################################
#	BUTTON NAME( ButtonTag )
########################################################################################################################
images/btn_search.gif						= Search
images/btn_reset.gif						= Reset
images/btn_update.gif						= Update
images/btn_loadtemplate.gif					= Load Template
images/btn_down_header.gif					= Download(Header)
images/btn_down.gif							= Download
images/btn_down_all.gif						= All Download
images/btn_down_sap.gif						= Download(SAP)
images/btn_return.gif						= Back
images/btn_order_enquiry.gif				= Order Status
images/btn_formatted_printing.gif			= Formatted Printing
images/btn_dpr_pdfodrprint.gif				= PDF Order Printing
images/btn_close.gif						= Close
images/btn_mod.gif							= Modify
images/btn_country_condition.gif			= Country Org. Setting
images/btn_download_product.gif				= Download Product
images/btn_upload_product.gif				= Upload Inputted Product
images/btn_addselectcart.gif				= Add To Cart
images/btn_delete.gif						= Delete
images/btn_del.gif							= Delete
images/btn_savetemplate.gif					= Save Template
images/btn_simulation.gif					= Simulation
images/btn_editorder.gif					= Edit Order
images/btn_ordercreate.gif					= Place Order
images/btn_down.gif							= Download
images/btn_up.gif							= Upload
images/btn_downtemplate.gif					= Down Template
images/btn_save.gif							= Save
images/btn_edit.gif							= Edit
images/btn_delAll.gif						= Delete All
images/btn_reg.gif							= Register
images/btn_dpr_tradepartner_auth.gif		= Trade Partner Authority Setting
images/btn_set.gif							= Setting
images/btn_down_template.gif				= Template Download
images/btn_shortage_eliminate.gif			= Shortage Eliminate
images/board/btn_regist.gif					= Register
images/board/btn_modify.gif					= Modify
images/board/btn_important.gif				= Important
images/board/btn_delete.gif					= Delete
images/board/btn_close.gif					= Close
images/board/btn_save.gif					= Save
images/board/btn_reg.gif					= Register
images/board/btn_search.gif					= Search
images/board/btn_showall.gif				= Show All
images/board/btn_completed.gif				= Completed
images/board/btn_back.gif					= Back
images/btn_regist_image.gif					= Image Register
images/btn_delete_image.gif					= Image Delete
images/btn_confirm.gif						= Confirm
images/btn_cancel.gif						= Cancel
images/menu_dpr_logout_off.gif				= LogOut
uploadManual/images/btn_upmanual.gif		= Order Upload Instruction

#images/login_jnj/login_btn_login.gif		= Log In


########################################################################################################################
#	sub_menu.jsp ( submenu img.alt )
########################################################################################################################
images/menu1_dpr_material_off.gif			= Material
images/menu2_dpr_material_list_off.gif		= Material Tree
images/menu2_dpr_material_img_list_off.gif	= Material Image
images/menu2_dpr_sellingsku_list_off.gif	= Selling Sku
images/menu2_dpr_plantsku_list_off.gif		= Plant Sku Exclusion
images/menu2_dpr_sellingskuplant_list_off.gif	= SKU Status Review
images/menu2_dpr_material_price_list_off.gif	= Material Price
images/menu2_dpr_materialupc_list_off.gif		= Material UPC
images/menu2_dpr_stopitemcfg_off.gif		= Stop Item Cfg
images/menu2_dpr_stopitem_off.gif			= Stop Item
images/menu2_dpr_packdealcfg_off.gif			= PackDeal Cfg
images/menu2_dpr_packdeal_off.gif			= PackDeal
images/menu2_dpr_freegoods_off.gif			= Free Quota Setting

images/menu1_dpr_partner_off.gif			= Partner
images/menu2_dpr_partylist_off.gif			= Trade Partner
images/menu2_dpr_country_list_off.gif		= Country
images/menu2_dpr_salesmov_list_off.gif		= Sales MOV
images/menu2_dpr_uommanage_off.gif			= UOM Management
images/menu2_dpr_rddmng_off.gif				= RDD Manage
images/menu2_dpr_partyoper_off.gif			= Party Oper
images/menu2_dpr_odrclosing_off.gif			= Order Closing
images/menu2_dpr_rcv_list_off.gif			= Recovery Comment

images/menu1_dpr_order_off.gif				= Order
images/menu2_dpr_odrstatus_off.gif			= Order Status
images/menu2_dpr_odrinput_off.gif			= Order Input
images/menu2_dpr_packdeal_off.gif			= Pack Deal
images/menu2_dpr_odrreport_off.gif			= Order Report
images/menu2_dpr_odrmod_off.gif				= Order Mod
images/menu2_dpr_billreport_off.gif			= Billing Report
images/menu2_dpr_productreq_list_off.gif	= Product Reqirement
images/menu2_dpr_moqitemcfg_off.gif			= MOQ Item Cfg
images/menu2_dpr_moqitem_off.gif			= MOQ Report

images/menu1_dpr_upload_off.gif				= Upload
images/menu2_dpr_custmst_off.gif			= Customer Master
images/menu2_dpr_prdtmst_off.gif			= Product Master
images/menu2_dpr_extmst_sjjp_off.gif		= Extra Master Data
images/menu2_dpr_extmst_off.gif				= Extra Master Data
images/menu2_dpr_pdfodrcmt_sjjp_off.gif		= PDF Order Comment
images/menu2_dpr_pdfodrcmt_off.gif			= PDF Order Comment
images/menu2_dpr_skulist_off.gif			= Selling SKU List
images/menu2_dpr_pcatedesc_off.gif			= Category Description
images/menu2_dpr_inventory_off.gif			= Inveotry
images/menu2_dpr_sellout_off.gif			= Sellout
images/menu2_dpr_customerid_off.gif			= Customer ID
images/menu2_dpr_skumap_off.gif				= SKU Mapping
images/menu2_dpr_idmapping_off.gif			= ID Mapping

images/menu1_dpr_log_off.gif				= Log
images/menu2_dpr_uploadlog_off.gif			= Upload
images/menu2_dpr_uploadlogkr_off.gif		= Upload(KR)

images/menu1_dpr_user_off.gif				= User
images/menu2_dpr_userinfo_off.gif			= User Info
images/menu2_dpr_usermgt_off.gif			= User Management
images/menu2_dpr_usersession_off.gif		= Access Status

images/menu1_dpr_faq_off.gif				= FAQ
images/menu1_dpr_inbox_off.gif				= Inbox
images/menu1_dpr_msgboard_off.gif			= Message Board
images/menu1_dpr_notice_off.gif				= Notice

########################################################################################################################
#	JSP NAME( ServletModel.forward )
########################################################################################################################
/jsp/dpr_order_input.jsp					= /jsp/dpr_order_input.m.jsp
/jsp/login.jsp								= /jsp/login.m.jsp


jsp.dpr_order_input.SEARCH_CART_ITEM_IND	= Search Cart Item?
jsp.dpr_order_input.GRP_ORDER_ITEM			= Item
jsp.MSG_SEARCH_COND_ORDER					= Order

jsp.BTN_SIDEBAR								= Sidebar
jsp.MSG_NAVMORE								= More

