#
#	File Name:	RBMColumnResource_en.properties
#	Version:	2.2.2c
#
#	Description:
#		ColumnResourceBundle\uC758 SYS\uC6A9, USR\uC6A9, RBM\uC6A9 subSet
#
#	Note:
#		SYSCode
#		SYSStdCode
#		SYSClassCode
#		USRParty
#		USRUser
#		USRUserSession
#		RBMBoard
#		RBMUploadLog
#		RBMUploadLogDetail
#
#	Modified	(YYYY/MM/DD)	Ver		Content
#	jbaek		2020/12/21		2.2.2c	multi-sold-to \uAE30\uB2A5 \uCD94\uAC00
#	jbaek		2018/10/30		2.2.2c	PartyLoginBlock \uAE30\uB2A5 \uCD94\uAC00
#	jbaek		2014/12/31		2.2.2	lastAccessUserAgent \uCD94\uAC00
#	stghr12		2008/03/31		2.2.1	RBMUploadLog, RBMUploadLogDetail \uCD94\uAC00
#	stghr12		2007/11/30		2.2.0	\uC601\uC5B4\uC9C0\uC6D0
#	stghr12		2007/04/30		2.1.0	version \uAD00\uB9AC
#

########################################################################################################################
#
#	[COL.]{columnKey}			{titlePattern}			Y|N	[{columnAttr}]					[{dataPattern}]
#	[COL.]{columnKey}%ATTR		{columnAttr}
#	[COL.]{columnKey}%DATA		{dataPattern}
#	[COL.]{columnKey}%HELP		{helpPattern}
#	GRP.{columnGroupKey}		{titlePattern}			[{columnAttr}]
#	GRP.{columnGroupKey}%COL	{columnKey}				[{titlePattern}]					[{columnAttr}]
#	LNK.{linkKey}				{hrefPattern}												[{titlePattern}]
#	LNK.{linkKey}%TITLE			{titlePattern}
#	LNK.{linkKey}%AUTH			{systemCode} {packageCode}
#	LNK.{linkKey}%COND			NOT_NULL|NOT_ZERO|EQUALS|CONTAINS {fieldKey} [{value1}[,{value2}[,...]]]
#	SFX.{suffixKey}				{suffixPattern}
#
########################################################################################################################


########################################################################################################################
#	PUBLIC
########################################################################################################################
PUBLIC:
	description					Description				Y	class='description'
	description.w200%ATTR		width='200'
	description.w300%ATTR		width='300'
	description.m60%DATA		$H{description~60}
	description.m30%DATA		$H{description~30}
	gln							GLN						Y	class='gln'
	partyRole					Type					Y	width='50' align='center'		${ECS_PARTYROLE_@partyRole}
	companyName.m18				Company Name			Y	width='120'						$H{companyName~18b}
	companyName.m18%HELP		$H{companyName}
	companyName.w120			Company Name			Y	width='120'
	companyName.desc			Company Name			Y	class='description'
	locationName.desc			Location Name			Y	class='description'
	locationName.w80			Loc Name				Y	width='80'
	locationName.w100			Location Name			Y	width='100'
	locationShortName.desc		Location Name			Y	class='description'
	gtin						GTIN					Y	class='gtin'
	gtin.s						GTIN					Y	class='gtin_s'
	gtin.s7						GTIN					Y	width='50' align='center'		${gtin~7~}
	itemName					Material Description	Y	class='description'
	itemName.w200%ATTR			width='200'
	itemName.w250%ATTR			width='250'

	buyerGln					Customer GLN			Y	class='gln'
	buyerCompanyName			Customer Comapany Name	Y	class='description'
	buyerCompanyName.w120		Customer Comapany Name	Y	width='120'
	buyerLocationName			Customer Location Name	Y	class='description'
	buyerLocationName.w100		Customer Location Name	Y	width='100'
	buyerPartyCode				Code					Y	width='60' align='center'
	buyerPartyRole				Type					Y	width='50' align='center'		${ECS_PARTYROLE_@buyerPartyRole}
	sellerGln					Seller GLN				Y	class='gln'
	sellerCompanyName			Seller Company Name		Y	class='description'
	sellerCompanyName.w120		Seller Company Name		Y	width='120'
	sellerLocationName			Seller Location Name	Y	class='description'
	sellerLocationName.w100		Seller Location Name	Y	width='100'
	sellerPartyCode				Seller Code				Y	width='60' align='center'
	sellerPartyRole				Type					Y	width='50' align='center'		${ECS_PARTYROLE_@sellerPartyRole}
	parentBuyerGln				Customer GLN			Y	class='gln'
	parentBuyerCompanyName		Customer Company Name	Y	class='description'
	parentSellerGln				Seller GLN				Y	class='gln'
	parentSellerCompanyName		Seller Company Name		Y	class='description'

	buyerGln.1					GLN						Y	class='gln'
	buyerCompanyName.1			Company Name			Y	class='description'
	buyerCompanyName.1.w120		Company Name			Y	width='120'
	buyerLocationName.1			Location Name			Y	class='description'
	buyerLocationName.1.w80		Loc Name				Y	width='80'
	buyerLocationName.1.w100	Location Name			Y	width='100'
	buyerPartyCode.1			Code					Y	width='60' align='center'
	buyerPartyRole.1			Type					Y	width='50' align='center'		${ECS_PARTYROLE_@buyerPartyRole}
	sellerGln.1					GLN						Y	class='gln'
	sellerCompanyName.1			Seller Name				Y	class='description'
	sellerCompanyName.1.w120	Seller Name				Y	width='120'
	sellerLocationName.1		Seller Name				Y	class='description'
	sellerLocationName.1.w100	Seller Name				Y	width='100'
	sellerPartyCode.1			Code					Y	width='60' align='center'
	sellerPartyRole.1			Type					Y	width='50' align='center'		${ECS_PARTYROLE_@sellerPartyRole}
	parentBuyerGln.1			GLN						Y	class='gln'
	parentBuyerCompanyName.1	Company Name			Y	class='description'
	parentBuyerCompanyName.1.w120%ATTR						width='120'
	parentSellerGln.1			GLN						Y	class='gln'
	parentSellerCompanyName.1	Company Name			Y	class='description'
	parentSellerCompanyName.1.w120%ATTR						width='120'

	qtyOfItemsPerCase			UOM						Y	width='70' align='right'		${qtyOfItemsPerCase#NF.INTEGER; %{MSG_EA}}
	qtyOfItemsPerCase.f			UOM						Y	width='80'						$H{caseName} $H{(:qtyOfItemsPerCase; %{MSG_EA})}
	qtyOfItemsPerCase.s			UOM						Y	width='45' align='right'		${qtyOfItemsPerCase#NF.INTEGER; %{MSG_EA}}
	qtyOfItemsPerCase.ss		UOM						Y	width='35' align='right'		${qtyOfItemsPerCase#NF.INTEGER; %{MSG_EA}}
	qtyOfItemsPerInnerPack		Pack Size				Y	width='70' align='right'		${qtyOfItemsPerInnerPack#NF.INTEGER; %{MSG_EA}}
	qtyOfItemsPerInnerPack.s	Pack<br>Size			Y	width='45' align='right'		${qtyOfItemsPerInnerPack#NF.INTEGER; %{MSG_EA}}
	qtyOfItemsPerInnerPack.ss	Pack<br>Size			Y	width='35' align='right'		${qtyOfItemsPerInnerPack#NF.INTEGER; %{MSG_EA}}

	createDateTime				Created					Y	class='date_ymd'				${createDateTime~~10}
	updateDateTime				Updated					Y	class='date_ymd'				${updateDateTime~~10}

	LNK.uinfo					JavaScript:userUserInfo("${uniqId}");						User ID Info
	LNK.pinfo					JavaScript:userPartyInfo("${partyId}");						Affiliate ID Info


PUBLIC.USR:
	partyId						Affiliate ID			Y	class='userid'
	partyName.w150				Affiliate Name			Y	width='150'
	partyName.desc				Affiliate Name			Y	class='description'
	userId						User ID					Y	class='userid'
	userName.w80				User Name				Y	width='80'
	userName.w150				User Name				Y	width='150'
	userName.desc				User Name				Y	class='description'
	uniqId						UNIQID					Y	class='userid'
	groupId						Group ID				Y	class='userid'
	groupName					Group Name				Y	width='80'						$H{groupName~10b}
	serviceStartDate			Service Starting Date	Y	class='date_ymd'
	serviceStartDate.md			Service Starting Date	Y	class='date_md'					${serviceStartDate~5~}
	serviceEndDate				Service Ending Date		Y	class='date_ymd'
	serviceEndDate.md			Service Ending Date		Y	class='date_md'					${serviceEndDate~5~}
	blockStartIsoDate			Block Starting Date		Y
	blockEndIsoDate				Block Ending Date		Y
	mtnceStartIsoDate			Maintenance Starting Date	Y
	mtnceEndIsoDate				Maintenance Ending Date		Y
	GRP.serviceDate				Service Date
	GRP.serviceDate%COL			serviceStartDate		Start
	GRP.serviceDate%COL			serviceEndDate			End
	GRP.blockIsoDate			Login Block
	GRP.blockIsoDate%COL		blockStartIsoDate		Start
	GRP.blockIsoDate%COL		blockEndIsoDate			End
	GRP.mtnceIsoDate			Maintenance
	GRP.mtnceIsoDate%COL		mtnceStartIsoDate		Start
	GRP.mtnceIsoDate%COL		mtnceEndIsoDate			End


########################################################################################################################
#	SYSCode
########################################################################################################################
SYSCode:
	%primaryKeys( code )
	code						Code					Y	width='70'
	code.s4						Code					Y	width='70'						${code~4~}
	name						Name					Y	class='description'
	displaySequence				Sequence				Y	width='70' align='center'

SYSCode%LIST:
	%defaultSortKeys( displaySequence )
	code.s4, name


########################################################################################################################
#	SYSStdCode
########################################################################################################################
SYSStdCode:
	%primaryKeys( code )
	code						Code					Y	class='std_code'
	name						Name					Y	class='description'
SYSStdCode.CURR:
	symbol						Symbol					Y	width='70'
SYSStdCode.UNIT:
	symbol						Symbol					Y	width='70'
	classCode					Type					Y	width='60' align='center'		${SYS_UNITCLASS_@classCode}

SYSStdCode%LIST:
	%defaultSortKeys( code )
	code, name
SYSStdCode.CURR%LIST:
	%defaultSortKeys( code )
	code, symbol, name
SYSStdCode.UNIT%LIST:
	%defaultSortKeys( code )
	code, classCode, symbol, name


########################################################################################################################
#	SYSClassCode
########################################################################################################################
SYSClassCode:
	%primaryKeys( code )
	%includeKeys( description )
	classCode					Level					Y	width='30' align='center'
	code						Code					Y	width='90' align='center'
	levelCode					Code					Y	width='90' align='center'
	lowerCount					No of SUBs				Y	width='90' align='right'
	name.w300					Name					Y	width='300'
	LNK.lower					JavaScript:linkReq("${code}");								$H{name} Lower Category
	LNK.menu1					JavaScript:linkMenuReq("${code}", true);					Pop-up Menu
	LNK.menu2					JavaScript:linkMenuReq("${code}", false);					Pop-up Menu

SYSClassCode%LIST:
	%defaultSortKeys( code )
	code, lowerCount#lower, name.w300#menu1, description.m60
SYSClassCode%LIST.LAST:
	%defaultSortKeys( code )
	code, name.w300#menu2, description.m60


########################################################################################################################
#	USRParty
########################################################################################################################
USRParty:
	%primaryKeys( partyId )
	%includeKeys( LNK.uinfo, LNK.pinfo )
	%includeKeys( createDateTime, updateDateTime )
	%includeKeys( PUBLIC.USR#partyId, PUBLIC.USR#partyName )
	%includeKeys( PUBLIC.USR#serviceStartDate, PUBLIC.USR#serviceEndDate, PUBLIC.USR#GRP.serviceDate )
	%includeKeys( PUBLIC.USR#blockStartIsoDate, PUBLIC.USR#blockEndIsoDate, PUBLIC.USR#GRP.blockIsoDate )
	%includeKeys( PUBLIC.USR#mtnceStartIsoDate, PUBLIC.USR#mtnceEndIsoDate, PUBLIC.USR#GRP.mtnceIsoDate )
	partyClass					Type					Y	width='70' align='center'		${USR_PARTY_CLASS_@partyClass}
	partyGln					GLN						Y	class='gln'
	adminUserName				Manager					Y	class='username_m'
	chargeStartDate				Charge Starting Date	Y	class='date_ymd'

	status						Status					Y	class='status_4'				${USR_PARTY_STATUS_@status}
	telephone					Tel						Y	class='tel'
	userCount					No of<br>Users			Y	class='count'

	LNK.menu					JavaScript:linkMenuReq("${partyId}", "${status}");			Pop-up Menu
	LNK.userList				JavaScript:userListReq("${partyId}");						User List
	LNK.userList%AUTH			USR		USRUser.LST
USRParty%LIST:
	%defaultSortKeys( partyName )
	partyId, partyName.desc#menu, userCount#userList, partyGln, serviceStartDate, serviceEndDate
	blockStartIsoDate, blockEndIsoDate, mtnceStartIsoDate, mtnceEndIsoDate, partyClass, status


########################################################################################################################
#	USRUser
########################################################################################################################
USRUser:
	%primaryKeys( uniqId, userId )
	%includeKeys( LNK.uinfo, LNK.pinfo )
	%includeKeys( createDateTime, updateDateTime )
	%includeKeys( PUBLIC.USR#partyId, PUBLIC.USR#partyName )
	%includeKeys( PUBLIC.USR#userId, PUBLIC.USR#userName, PUBLIC.USR#uniqId )
	%includeKeys( PUBLIC.USR#groupId, PUBLIC.USR#groupName )
	%includeKeys( PUBLIC.USR#serviceStartDate, PUBLIC.USR#serviceEndDate, PUBLIC.USR#GRP.serviceDate )
	partyClass					Company Type			Y	class='class' align='center'	${USR_PARTY_CLASS_@partyClass}
	partyGln					GLN						Y	class='gln'
	chargeStartDate				Charge Starting Date	Y	class='date_ymd'
	ediId						EDI-ID					Y	class='userid'
	gln							GLN						Y	class='gln'
	userGln						GLN						Y	class='gln'
	userClass					User Type				Y	width='80' align='center'		${USR_USER_CLASS_@userClass}
	department					Department				Y	width='80'						$H{department~10}
	position					Position				Y	width='80'						$H{position~10}
	email.w150					E-mail					Y	width='150'
	email.w250					E-mail					Y	width='250'
	telephone					Tel						Y	class='tel'
	mobilephone					Mobile					Y	class='tel'
	fax							FAX						Y	class='tel'
	availAccessCount			Concurrent Access		Y	class='count_s'
	status						Status					Y	class='status_4'				${USR_USER_STATUS_@status}
	groupName%ATTR				width='150'
	groupName%DATA				${groupName}
	employeeSource				Map Src.				N	class='pcode'
	employeeId					Emp. Id					N	class='pcode'					$f{decode(employeeSource,S,${employeeId},)}
	employeeIds					Emp. Id					N	class='pcode'
	soldPartyOrgCode			Org. Cd					N	class='pcode'
	soldPartyCode				Sold to					N	class='pcode'
	soldPartyCodes				Sold to					N	width='250'				$f{decode(${empPartyCodes},,$f{decode(${usrPartyCodes},,,USR: ${usrPartyCodes})},$f{decode(${usrPartyCodes},,EMP: ${empPartyCodes},EMP: ${empPartyCodes}<br>USR: ${usrPartyCodes})})}
	status.name					Status					Y	class='status_4'				$f{decode(status,00,Active,99,Inactive,LK,Locked,PW,Expired,)}
	usrOrgEmpPtyIds				Emp. Sold to			N	class='pcode'

	LNK.menu					JavaScript:linkMenuReq("${uniqId}", "${partyId}", "${userId}");		Pop-up Menu

USRUser%LIST:
	%defaultSortKeys( userName )
	userId, userName.w150#menu, groupName, employeeIds/MSP, soldPartyCodes/MSP, department, telephone, email.w150, serviceStartDate, serviceEndDate, userClass, status
USRUser.MSP%DOWN:
	%defaultSortKeys( userId, employeeId, soldPartyOrgCode, soldPartyCode )
	userId, userName.w150, soldPartyOrgCode, employeeId, soldPartyCode, email.w150, status.name, usrOrgEmpPtyIds


########################################################################################################################
#	USRUserSession
########################################################################################################################
USRUserSession:
	%primaryKeys( sessionId )
	%includeKeys( LNK.uinfo, LNK.pinfo )
	%includeKeys( PUBLIC.USR#partyId, PUBLIC.USR#partyName )
	%includeKeys( PUBLIC.USR#userId, PUBLIC.USR#userName, PUBLIC.USR#uniqId )
	%includeKeys( PUBLIC.USR#groupId, PUBLIC.USR#groupName )
	ip							IP						Y	width='90' align='center'
	loginDateTime				Login Time				Y	width='70' align='center'		${loginDateTime~5~16}
	lastAccessDateTime			Last Access				Y	width='70' align='center'		${lastAccessDateTime~5~16}
	lastAccessTitle				Last Access Function	Y	width='150' align='left'
	lastAccessTitle.desc		Last Access Function	Y	class='description'
	lastAccessUserAgent.desc	Last Access UserAgent	Y	class='description'

	LNK.menu					JavaScript:linkMenuReq("${partyId}", "${uniqId}");			Pop-up Menu

USRUserSession%LIST:
	%defaultSortKeys( lastAccessDateTime#DESC )
	userId, userName.w150#menu, ip, loginDateTime, lastAccessDateTime, lastAccessTitle
USRUserSession%LIST.ALL:
	%defaultSortKeys( lastAccessDateTime#DESC )
	partyId, partyName.w150#menu, userId, userName.w150, ip, loginDateTime, lastAccessDateTime, lastAccessTitle


########################################################################################################################
#	RBMBoard
########################################################################################################################
RBMBoard:
	%primaryKeys( boardNumber )
	boardClassName.w80			Type					N	width='80'
	boardNumber					No						N	class='number'
	noticeStartDate				Start Date				N	class='date'					${noticeStartDate~~10}
	noticeEndDate				End Date				N	class='date'					${noticeEndDate~~10}
	title.desc					Title					N	class='description'
	title.desc.rd%DATA			$f{decode(readedByUser,N,<b>$H{title}</b>,$H{title})}
	registUserName				Writer					N	class='username'
	createDateTime				Written					N	class='date'					${createDateTime~~10}
	readedUserCount				Page View				N	class='count'

	LNK.info					JavaScript:infoReq("${boardNumber}");						Info
RBMBoard%LIST:
	boardNumber, title.desc/RD_N, title.desc.rd#info/RD_Y, registUserName, createDateTime, readedUserCount
RBMBoard%LIST.ALL:
	boardNumber, title.desc/RD_N, title.desc.rd#info/RD_Y, registUserName, noticeStartDate, noticeEndDate, createDateTime

########################################################################################################################
#	RBMUploadLog
########################################################################################################################
RBMUploadLog:
	%primaryKeys( logId )
	uploadTypeName				Type					Y	width='100'
	userName					User					Y	class='username'
	startDateTime				Started					Y	class='date_ymdhi'				${startDateTime~~16}
	startDateTime.ymd			Uploaded				Y	class='date'					${startDateTime~~10}
	startDateTime.hi			Started					Y	class='date_md'					${startDateTime~11~16}
	endDateTime					Ended					Y	class='date_ymdhi'				${endDateTime~~16}
	endDateTime.hi				Ended					Y	class='date_md'					${endDateTime~11~16}
	lineCount					No of Line				Y	width='50' align='right'		${lineCount#NF.INTEGER}
	successCount				No of Success			Y	width='50' align='right'		${successCount#NF.INTEGER}
	warningCount				No of Warning			Y	width='50' align='right'		${warningCount#NF.INTEGER}
	errorCount					No of Error				Y	width='50' align='right'		${errorCount#NF.INTEGER}
	message						Result Message			Y	class='description'
	status						Status					Y	class='status_4'				${RBM_UPLOADLOG_STATUS_@status}
	LNK.menu					JavaScript:linkMenuReq("${logId}");							Pop-up Menu

	GRP.count					No of
	GRP.count%COL				lineCount				Line
	GRP.count%COL				successCount			Success
	GRP.count%COL				warningCount			Warning
	GRP.count%COL				errorCount				Error

RBMUploadLog%LIST:
	%defaultSortKeys( startDateTime#DESC )
	uploadTypeName, message#menu, lineCount, successCount, warningCount, errorCount, startDateTime, userName, status


########################################################################################################################
#	RBMUploadLogDetail
########################################################################################################################
RBMUploadLogDetail:
	%primaryKeys( logId )
	lineNumber					No						Y	class='number'
	lineName					Line					Y	width='350'
	message						Result Message			Y	class='description'
	status						Result					Y	class='status_4'				${RBM_UPLOADLOG_LINESTATUS_@status}

RBMUploadLogDetail%LIST:
	%defaultSortKeys( lineNumber )
	lineNumber, lineName, message, status
