<%--
	File Name:	include_dpr_warning.inc
	Version:	2.2.0

	Description:

	Note:

	Modified	(YYYY/MM/DD)	Ver		Content
	lsinji		2008/09/26		2.2.0	create
--%>
<style type='text/css'><!--
	div.warning {
		background: #EFEFEF;
		line-height: 130%;
		margin: 0 50px;
		padding: 1px 10px;
		padding-top: 5px;
	}

	div.warning span {
		font: bold; color: #9E0000;
	}
//--></style>

	<div class='warning'>
		<mtl:message key="jsp.include_dpr_warning.MSG_WARNING_NOTICE"/>
	</div>
