
# webapp
webappRootPath		=		/app/dpr/dportal/webapp-dpr/

# log4javascript
# debugJS: log4javascript popup ui
# traceJS: log4javascript user action event logging
# useClientLogging: ajax send log4javascript logging to server side logging.
#debugJS				=	N
#traceJS				=	Y
#useClientLogging	=	Y